# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                 FUNCTIONS                                  │
# └────────────────────────────────────────────────────────────────────────────┘

[functions.extract_names]
type = "json"
output_schema = "functions/extract_names/output_schema.json"

[functions.extract_names.variants.baseline]
type = "chat_completion"
model = "openai::gpt-4o-mini"
json_mode = "strict"
system_template = "functions/extract_names/baseline/system_template.txt"
