[package]
name = "cursorzero"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
git2 = "0.20.1"
tree-sitter = "0.25.3"
tree-sitter-rust = "0.24.0"

[dev-dependencies]
