[package]
name = "cursorzero"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
git2 = "0.20.1"

[dev-dependencies]
