[project]
name = "data-extraction-ner"
version = "0.0.0"
description = "Example: Optimizing Data Extraction (NER) with TensorZero"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "altair",
    "ipykernel",
    "notebook",
    "pandas",
    "tensorzero",
]
