[project]
name = "tensorzero-recipe-sft-unsloth-demonstrations"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bitsandbytes",
    "clickhouse-connect",
    "ipykernel",
    "minijinja",
    "notebook",
    "numpy",
    "pandas",
    "toml",
    "unsloth",
]
