name: General Checks

on:
  push:
  merge_group:
  pull_request:
    branches: ["main"]

env:
  FORCE_COLOR: 1
  TENSORZERO_CLICKHOUSE_URL: "http://chuser:chpassword@localhost:8123/tensorzero"

jobs:
  validate:
    strategy:
      matrix:
        os: [macos-15-large, macos-15-xlarge]
    # runs-on: namespace-profile-tensorzero-8x16
    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest, cargo-deny, and cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-deny,cargo-hack

      - name: Test (Rust)
        run: |
          cargo test-unit ${{vars.CARGO_NEXTEST_ARGS}}